// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace vulnerable_cookie_swap {
	
	
	public partial class Default {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Label lblusername;
		
		protected System.Web.UI.WebControls.TextBox username;
		
		protected System.Web.UI.WebControls.Label lblpassword;
		
		protected System.Web.UI.WebControls.TextBox password;
		
		protected System.Web.UI.WebControls.Button button1;
	}
}
